export class PostProcessor {
  constructor() {
    this.processors = {
      grbl: (gcode) => this._grbl(gcode),
      marlin: (gcode) => this._marlin(gcode),
      smoothie: (gcode) => this._smoothie(gcode),
      linuxcnc: (gcode) => this._linuxcnc(gcode)
    };
  }

  process(gcode, type) {
    if (!type || type === 'none') return gcode;
    const proc = this.processors[type];
    if (!proc) return gcode;
    return proc(gcode);
  }

  getTypes() {
    return Object.keys(this.processors);
  }

  register(name, fn) {
    this.processors[name] = fn;
  }

  _grbl(gcode) {
    return '$H\nG92 X0 Y0 Z0\n' + gcode + '\nM2';
  }

  _marlin(gcode) {
    let result = 'G21 ; mm\nG90 ; abs\nG28 ; home\n';
    result += gcode;
    result += '\nG28 X0 Y0 ; home XY';
    return result;
  }

  _smoothie(gcode) {
    return gcode;
  }

  _linuxcnc(gcode) {
    let result = '(Generated by OpenBuilds CAM Engine)\n';
    result += 'G17 G21 G40 G49 G80 G90 G94\n';
    result += 'G54\n';
    result += gcode + '\n';
    result += 'M30\n%';
    return result;
  }

  addHeader(gcode, header) {
    return header + '\n' + gcode;
  }

  addFooter(gcode, footer) {
    return gcode + '\n' + footer;
  }

  replaceCommands(gcode, replacements) {
    let result = gcode;
    for (const [from, to] of Object.entries(replacements)) {
      const regex = new RegExp(`\\b${from}\\b`, 'g');
      result = result.replace(regex, to);
    }
    return result;
  }

  scaleCoordinates(gcode, scaleX, scaleY, scaleZ) {
    return gcode.replace(
      /([XYZ])(-?\d+\.?\d*)/g,
      (match, axis, val) => {
        const scale = axis === 'X' ? scaleX :
          axis === 'Y' ? scaleY : scaleZ;
        return axis + (parseFloat(val) * scale).toFixed(3);
      }
    );
  }

  offsetCoordinates(gcode, offsetX, offsetY, offsetZ) {
    return gcode.replace(
      /([XYZ])(-?\d+\.?\d*)/g,
      (match, axis, val) => {
        const offset = axis === 'X' ? offsetX :
          axis === 'Y' ? offsetY : offsetZ;
        return axis + (parseFloat(val) + offset).toFixed(3);
      }
    );
  }
}
